// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZzRpKSPmTcON8EjO4VQnHEVmDtGLZxig',
    appId: '1:717619231725:web:35ff4d1330c12ec58405e4',
    messagingSenderId: '717619231725',
    projectId: 'echobot-1010m',
    authDomain: 'echobot-1010m.firebaseapp.com',
    storageBucket: 'echobot-1010m.firebasestorage.app',
    measurementId: 'G-30NFK0PGFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZgPA9V6CXNPPtPPXrQocXPcu9c4bJdPM',
    appId: '1:717619231725:android:09bef428426b00188405e4',
    messagingSenderId: '717619231725',
    projectId: 'echobot-1010m',
    storageBucket: 'echobot-1010m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQmEjD4kIFCKqQwR3TQwiU6TYbghHd_TU',
    appId: '1:717619231725:ios:b63008ceeee8b6458405e4',
    messagingSenderId: '717619231725',
    projectId: 'echobot-1010m',
    storageBucket: 'echobot-1010m.firebasestorage.app',
    iosBundleId: 'com.example.echobotApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQmEjD4kIFCKqQwR3TQwiU6TYbghHd_TU',
    appId: '1:717619231725:ios:b63008ceeee8b6458405e4',
    messagingSenderId: '717619231725',
    projectId: 'echobot-1010m',
    storageBucket: 'echobot-1010m.firebasestorage.app',
    iosBundleId: 'com.example.echobotApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZzRpKSPmTcON8EjO4VQnHEVmDtGLZxig',
    appId: '1:717619231725:web:16a41a7d9cccd0348405e4',
    messagingSenderId: '717619231725',
    projectId: 'echobot-1010m',
    authDomain: 'echobot-1010m.firebaseapp.com',
    storageBucket: 'echobot-1010m.firebasestorage.app',
    measurementId: 'G-M9NJG7XM1L',
  );
}
